# -*- coding: utf-8 -*-
"""ATS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y7L2dIm5XW4jmXnfeiHRrxBDGJ7oEeco
"""

#Description
#A mini ats(applicant tracking system) will give you a score based on the similiarity of the  job description and your resume.

#install docx2txt using pip

##pip install docx2txt

#import library
import docx2txt

#load data 
from google.colab import files
uploaded = files.upload()

#store the resume in a variable
resume = docx2txt.process("your_resume.csv")

#print the resume 
print(resume)

#store the job description file in a variable
job_description = docx2txt.process("job_description.csv")

#print the job description
print (job_description)

#list of a text
text = [resume,job_description]

#import sklear
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text)

from sklearn.metrics.pairwise import cosine_similarity
#print similiarity score
print("\nSimiliarity Score:")
print(cosine_similarity(count_matrix))

#get the percentage

matchPercentage = cosine_similiarity(count_matrix)[0][1]*100
matchPercentage = round(matchPercentage,2)#rounding to two decimal
print ("your resume mathces about:"+str(matchPercentage)+"% of your job description")







